import type Database from 'better-sqlite3';
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { resolveRepoPath } from '../db/queries.js';
import { criteriaOf, criterionKey, parseJsonArray, specKey, type SpecRow } from './specs.js';

export function renderSpecMarkdown(spec: SpecRow, db: Database.Database): string {
  const criteria = criteriaOf(db, spec.id);
  const constraints = parseJsonArray(spec.constraints);
  const outOfScope = parseJsonArray(spec.out_of_scope);
  const list = (items: string[]) => items.map(i => `- ${i}`).join('\n');
  const lines = [
    '<!-- Generated by mindpm from its database. Do not edit: changes here are never read back. -->',
    '',
    `# ${specKey(spec)}: ${spec.title}`,
    '',
    `Version ${spec.version} · ${spec.status} · risk: ${spec.risk_level}` +
      (spec.approved_by ? ` · approved by ${spec.approved_by}${spec.approved_at ? ` on ${spec.approved_at}` : ''}` : ''),
    '',
    '## Objective',
    '',
    spec.objective,
    '',
    '## Why',
    '',
    spec.why,
  ];
  if (spec.approach) lines.push('', '## Approach', '', spec.approach);
  if (constraints.length) lines.push('', '## Constraints', '', list(constraints));
  if (outOfScope.length) lines.push('', '## Out of scope', '', list(outOfScope));
  lines.push('', '## Acceptance criteria', '');
  for (const c of criteria) {
    const verify = c.verify_ref ? `${c.verify_kind}: \`${c.verify_ref}\`` : c.verify_kind;
    lines.push(`- **${criterionKey(spec, c)}** ${c.statement} _(${verify})_`);
  }
  return lines.join('\n') + '\n';
}

// Write specs/SPEC-<seq>.md into the project's repo. Called only after the
// approving transaction commits, so a file error never rolls back an
// approval; it comes back as a warning instead. Agents never stage specs/;
// a human commits these files.
export function writeSpecFile(db: Database.Database, specId: string): { path: string | null; warning: string | null } {
  const spec = db.prepare('SELECT * FROM specs WHERE id = ?').get(specId) as SpecRow | undefined;
  if (!spec) return { path: null, warning: 'Spec not found when writing its file.' };
  const repo = resolveRepoPath(spec.project_id);
  if (!repo) {
    return { path: null, warning: `No repo_path set for this project, so ${specKey(spec)}.md was not written. Set one with set_project_repo_path.` };
  }
  const path = join(repo, 'specs', `${specKey(spec)}.md`);
  try {
    mkdirSync(join(repo, 'specs'), { recursive: true });
    writeFileSync(path, renderSpecMarkdown(spec, db), 'utf8');
    return { path, warning: null };
  } catch (err) {
    return { path: null, warning: `Could not write ${path}: ${(err as Error).message}` };
  }
}
